### ISSUE TITLE
SSL certification fails

### ISSUE THREAD

**Issue by atombender** [renderedtext/semaphore-status#2]
```
# sst
Please enter authentication token for your Semaphore account:
[…]
Token successfully saved.
/usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/net/http.rb:799:in `block in connect'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/net/http.rb:799:in `connect'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/net/http.rb:744:in `start'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/open-uri.rb:306:in `open_http'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/open-uri.rb:775:in `buffer_open'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/open-uri.rb:201:in `catch'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/open-uri.rb:201:in `open_loop'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/1.9.1/open-uri.rb:33:in `open'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/semaphore-status-0.0.2/lib/semaphore-status.rb:14:in `initialize'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/semaphore-status-0.0.2/bin/sst:64:in `new'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/semaphore-status-0.0.2/bin/sst:64:in `get_projects'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/semaphore-status-0.0.2/bin/sst:88:in `<top (required)>'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/bin/sst:23:in `load'
    from /usr/local/opt/rbenv/versions/1.9.3-p385/bin/sst:23:in `<main>'
```

I have confirmed with `curl` that semaphoreapp.com's cert is fine, so I don't know what is going on there.

**Comment by rastasheep** [comment]
I tried to reproduce your issue and i didn't succeed.

Which OS you use, and how you installed ruby?

Can you try to curl semaphore api manually from irb?

``` ruby
require 'open-uri'
open('https://semaphoreapp.com/api/v1/projects?auth_token=YOUR_TOKEN').read
```

**Comment by atombender** [comment]
I get the same error. I'm on OS X, Ruby installed through Homebrew.

```
# ruby -v
ruby 1.9.3p385 (2013-02-06 revision 39114) [x86_64-darwin12.2.0]
```

I believe it's compiled against the system-provded OpenSSL. Will try building against a newer version.

**Comment by atombender** [comment]
May be a known problem: http://martinottenwaelter.fr/2010/12/ruby19-and-the-ssl-error/.

**Comment by atombender** [comment]
Confirmed to work with the CA cert workaround.

**Comment by rastasheep** [comment]
Great,

Thanks again for submitting issue.

Let me know if you have any suggestions for improving this gem, or Semaphore app in general.
 :smiley:
